[global_tags]
  organization_name = "stackit_organization_name"
  space_name = "stackit_space_name"
  application_name = "stackit_application_name"

[agent]
  interval = "20s"
  round_interval = true
  metric_batch_size = 500
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = true
  omit_hostname = false

[[outputs.http]]
    url = "prom_remote_write_url"
    username = "prom_remote_write_user"
    password = "prom_remote_write_passwd"
    data_format = "prometheusremotewrite"

[outputs.http.headers]
    Content-Type = "application/x-protobuf"
    Content-Encoding = "snappy"
    X-Prometheus-Remote-Write-Version = "0.1.0"

[[inputs.mysql]]
    servers = ["mysql_user:mysql_password@tcp(mysql_host:3306)/mysql_name"]

[[inputs.rabbitmq]]
  url = "https://rabbitmq_user:rabbitmq_password@rabbitmq_host:15672"

[[inputs.redis]]
    servers = ["tcp://:redis_password@redis_host:6379"]

